### ISSUE TITLE
XRP transactions failing

### ISSUE THREAD

**Issue by AlfieC** [ZelCore-io/Zelcore#75]
Hi, all XRP transaction show rejected by XRP network. In logs this shows:

`2023-03-21T19:04:34.816Z          Error while obtaining ripple balance
2023-03-21T19:04:34.816Z          Request failed with status code 404
AxiosError: Request failed with status code 404
    at file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26793331
    at XMLHttpRequest.d (file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26793476)
2023-03-21T19:04:59.900Z          Error while obtaining kadena transactions
2023-03-21T19:04:59.900Z          timeout of 50000ms exceeded
AxiosError: timeout of 50000ms exceeded
    at s.ontimeout (file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26794243)
2023-03-21T19:04:59.902Z          timeout of 50000ms exceeded
AxiosError: timeout of 50000ms exceeded
    at s.ontimeout (file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26794243)
2023-03-21T19:04:59.901Z          Error while obtaining kadena transactions
2023-03-21T19:05:44.116Z          {"name":"NewsBTC","feed":"https://www.newsbtc.com/feed","site":"https://www.newsbtc.com","about":"NewsBTC is a premier news and resource platform, working since October 2013 to bring quality news content, reviews, technical analysis and other unique insights to the ever-growing cryptocurrency community.","pic":"@/assets/news/newsbtc.svg"}
2023-03-21T19:05:44.116Z          Network Error
AxiosError: Network Error
    at s.onerror (file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26794020)
2023-03-21T19:05:46.945Z          Request failed with status code 404
2023-03-21T19:05:46.945Z          Error while obtaining ripple balance
AxiosError: Request failed with status code 404
    at file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26793331
    at XMLHttpRequest.d (file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26793476)
2023-03-21T19:05:47.005Z          {"name":"Ripple Blog","feed":"https://ripple.com/insights/feed","site":"https://ripple.com","about":"Ripple is centralized payment protocol used to hold fiat currency, cryptocurrency and commodities. Ripple has been adopted by banks and payment networks as settlement infrastructure technology.","pic":"@/assets/logos/XRP.svg"}
2023-03-21T19:05:47.006Z          Request failed with status code 404
AxiosError: Request failed with status code 404
    at file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26793331
    at XMLHttpRequest.d (file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26793476)
2023-03-21T19:05:47.180Z          {"name":"NewsBTC","feed":"https://www.newsbtc.com/feed","site":"https://www.newsbtc.com","about":"NewsBTC is a premier news and resource platform, working since October 2013 to bring quality news content, reviews, technical analysis and other unique insights to the ever-growing cryptocurrency community.","pic":"@/assets/news/newsbtc.svg"}
2023-03-21T19:05:47.180Z          Network Error
AxiosError: Network Error
    at s.onerror (file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26794020)
2023-03-21T19:06:16.996Z          Error while obtaining ripple balance
2023-03-21T19:06:16.996Z          Request failed with status code 404
AxiosError: Request failed with status code 404
    at file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26793331
    at XMLHttpRequest.d (file:///C:/Users/USER/AppData/Local/Programs/zelcore/resources/app.asar/dist/electron/node_vendors.js:2:26793476)`

**Comment by TheTrunk** [comment]
Hi,
Thank you for reaching out.
We will be releasing desktop fiz for XRP sending in the next few hours.
Sorry for any inconvenience caused.

**Comment by AlfieC** [comment]
Do we have an approx eta? I have an XRP transaction that I've been waiting to send but as of yet haven't been able to.

**Comment by TheTrunk** [comment]
> Do we have an approx eta? I have an XRP transaction that I've been waiting to send but as of yet haven't been able to.

Hi yes, 
v6.7.1 was just released :)
